version: '3.0'

expectations:
  population_size: 15000

actions:

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv
      
  generate_study_population_1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-09-01 to 2019-04-01 by month" --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv
  
  generate_study_population_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-05-01 to 2019-11-01 by month" --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input*.csv
  
  generate_study_population_3:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-12-01 to 2020-06-01 by month" --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/inpu*.csv
  
  generate_study_population_4:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-07-01 to 2021-05-01 by month" --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/inp*.csv
        
  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py
    needs: [generate_study_population_1, generate_study_population_2, generate_study_population_3, generate_study_population_4, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/in*.csv
        
  patient_count:
    run: python:latest python analysis/get_patient_count.py
    needs: [join_ethnicity]
    outputs:
      moderately_sensitive:
        csv: output/patient_count.csv

  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/measure_*_rate.csv

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/notebook.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [join_ethnicity, generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/notebook.html
        figures: output/measure_*.jpeg
        total_csv: output/doac_rate_total.csv
        csvs: output/current_doac_*.csv
  
  combine:
      run: python:latest python analysis/combined_analysis.py
      outputs:
        moderately_sensitive:
          measure_csv: released_outputs/combined_rate.csv
          count: released_outputs/count.jpeg
          rate: released_outputs/rate.jpeg

