version: '3.0'

expectations:
  population_size: 15000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-01 to 2021-04-01 by month" --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv



  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
      needs: [generate_study_population]
      outputs:
        moderately_sensitive:
          measure_csv: output/measure_*.csv


  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/measures_notebook.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
    needs: [generate_study_population, generate_measures]
    outputs:
      moderately_sensitive:
        notebook: output/measures_notebook.html
        csv: output/check.csv